### ISSUE TITLE
ru.index.community не работает :(

### ISSUE THREAD

**Issue by LuckyCoders** [fediland/fediland.github.io#25]
[«RU Fedi»](https://ru.index.community/) — каталог серверов и групп русскоязычного созвездия Fediverse.

[https://web.archive.org/web/20230606060037/https://ru.index.community/](https://web.archive.org/web/20230606060037/https://ru.index.community)

**Comment by skobkin** [comment]
> https://web.archive.org/web/20230606060037/https://ru.index.community

Он там нормально не работает. Заменим на "официальный" каталог пока что, пожалуй.

Спасибо за репорт.

**Comment by Minoru** [comment]
Если кто-то хочет воскресить тот сервис, код здесь: https://inex.dev/inex/index.community
